### ISSUE TITLE
uptime_check_ssl_cert does not accept https for protocol

### ISSUE THREAD

**Issue by kpocius** [uptime-com/terraform-provider-uptime#25]
```
│ Error: Invalid protocol for SSL Cert check: https
│
│   with uptime_check_ssl_cert.expiry,
│   on uptime_check_ssl_cert.tf line 16, in resource "uptime_check_ssl_cert" "expiry":
│   16:   protocol           = "https"
```
If I create the resource with `protocol = "http"` it gets saved as `protocol = "https"` in the state and shows a diff upon every subsequent plan.

**Comment by bazzisoft** [comment]
@mikluko I think this is due to a recent upgrade of the SSL Cert Check, where the `protocol` field was deprecated in favour of `sslconfig.ssl_cert_protocol` and the new default is `https`. The above behaviour is the result of maintaining backwards compatibility with the deprecated field, but it appears to mess with Terraform's state as described above. Is this something we can adjust in the provider?

**Comment by mikluko** [comment]
Good catch. 

Yes, it is possible to handle that on API client library and TF provider side.

**Comment by kpocius** [comment]
The resource name change from `uptime_check_ssl_cert` to `uptime_check_sslcert` and it no longer accepts `days_before_expiry` attribute. After updating the resource name and removing offending attribute, the apply fails with the following:
```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to uptime_check_sslcert.test, provider "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an unexpected new value: .config: was absent, but now present.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by kpocius** [comment]
The resource does get created though, with "Before expiry" set to `0`.

**Comment by mikluko** [comment]
@kpocius [v2.0.0-beta.2](https://registry.terraform.io/providers/uptime-com/uptime/2.0.0-beta.2) has been released. The release contains update to `uptime_check_sslcert` resource which addresses inconsistent state issue. 

Please note backwards incompatible change. E.g. `config` becomes attribute rather than nested block: 

```
resource uptime_check_sslcert test {
  ...
  config {
    crl = true
  }
}
```

should become 

```
resource uptime_check_sslcert test {
  ...
  config = {
    crl = true
  }
}
```

According to [Terraform provider developmet docs](https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/blocks-computed) that is the recommended way. Sorry for the inconvenience.
