### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by karlo-hiq** [uptime-com/terraform-provider-uptime#90]
Getting the following errors when applying Terraform
`╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to uptime_check_http.http_example.com_8443, provider
│ "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an unexpected new value: .port: was cty.NumberIntVal(8443), but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

`╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to uptime_check_http.http_example.com, provider "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an unexpected
│ new value: .headers: element "api-key" has vanished.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

**Comment by gigovich** [comment]
Hi @karlo-hiq, thank you.
We'll try to reproduce it and fix it in the nearest releases.

**Comment by gigovich** [comment]
@karlo-hiq, the first problem is that when we create an HTTP check with a custom port, we also need to set the port value in the port property. The latest version of the provider now checks for this.

The second issue is on the API side. Unfortunately, you need to use capital letters for the headers. Please use Api-Key instead of api-key.

I’m closing this issue for now unless there’s something else related to these cases.

Sorry for the delay.

Let me know if you need any more changes!
